first option
ok-technopolis-2020/Solyankin-Ilia pull request #2
Opened 2020-10-30 13:36 UTC by Evil-Enot

2020-10-31 11:56 UTC, fromanywhere requested changes
Пора бы начинать графику

2020-10-31 11:56 UTC, fromanywhere commented on Styles/style.css
> +.main_select_all {
это немного странный бэм, но в принципе компонентное разбиение есть, окей...

2020-10-31 11:56 UTC, fromanywhere commented on Styles/style.css
> +input[type="checkbox"]{
убираем такие селекторы, переходим на классы

2020-10-31 11:56 UTC, fromanywhere commented on Styles/style.css
> +    height: 64px;
порвется и по горизонтали и по вертикали 
![image](https://user-images.githubusercontent.com/1042969/97778548-f1226f00-1b88-11eb-8b54-87148c55641f.png)

2020-10-31 11:56 UTC, fromanywhere commented on Styles/style.css
> +    background-color: #ffffff;
утеряны тени

2020-10-31 11:56 UTC, fromanywhere commented on index.html
> +                            <input type="radio" class="task_filter_item_input" value="Active" />
из-за отсутствия name оно всё еще работает не так как должно

2020-10-31 11:56 UTC, fromanywhere commented on Styles/style.css
> +li:hover .tasks_item_delete {
на фокус крестика его тоже рисовать нужно

2020-11-01 21:55 UTC, fromanywhere requested changes
ну почти

2020-11-01 21:55 UTC, fromanywhere commented on Styles/style.css
> +    background-color: #ffffff;
Всё еще утеряны тени

2020-11-01 21:55 UTC, fromanywhere commented on index.html
> +                            <input type="radio" class="task_filter_item_input" name="filter" value="Active" />
Тут какой-то один пункт должен быть выбран

2020-11-01 21:55 UTC, fromanywhere commented on Styles/style.css
> +    border-bottom: 1px solid #E6E6E6;
видно, что граница на стыке с бордером двоится. Лучше .todo_tasks_item + .todo_tasks_item {border-top}

2020-11-01 21:55 UTC, fromanywhere commented on Styles/style.css
> +    background: url("../images/completed.png") no-repeat center;
основная проблема — нет ретины нигде

2020-11-01 21:55 UTC, fromanywhere commented on Styles/style.css
> +    border-color: #979592;
чот цвет мимо макета. Заодно и фокус дописать

2020-11-01 21:55 UTC, fromanywhere commented on Styles/style.css
> +    border: solid transparent 1px;
наверняка же бордер-радиус еще по макету

2020-11-02 09:54 UTC, Evil-Enot commented on Styles/style.css
> +    background-color: #ffffff;
Подскажите, пожалуйста, здесь речь идет о каких именно тенях? Не могу понять просто, где их не хватает

2020-11-02 10:07 UTC, fromanywhere commented on Styles/style.css
> +    background-color: #ffffff;
![image](https://user-images.githubusercontent.com/1042969/97855837-6b2f3100-1d0c-11eb-9d11-d1e58399a9cb.png)

2020-11-02 10:19 UTC, Evil-Enot commented on Styles/style.css
> +    background-color: #ffffff;
А, хорошо, понял

2020-11-02 11:27 UTC, fromanywhere approved these changes
Апрув авансом

2020-11-02 11:27 UTC, fromanywhere commented on Styles/style.css
> +        background-size: 28px 16px;
тут очень смешно — из-за того, что background — полная форма записи, она переопределяет background-size, и поэтому он не работает. Его нужно ниже написать ) Кстати, по-хорошему он должен быть кратен размерам картинки, т.е. 24 х 12

2020-11-02 11:27 UTC, fromanywhere commented on Styles/style.css
> +    .task__checkbox:checked + .task__status-icon {
не работает потому что списывать нехорошо

2020-11-02 11:33 UTC, Evil-Enot commented on Styles/style.css
> +    .task__checkbox:checked + .task__status-icon {
Извините, просто не до конца понял этот момент :с

2020-11-02 15:51 UTC, merged